dist: trusty
language: java
install: ant deps

before_install:
  # Install Buck
  - test -d $HOME/buck || git clone --branch tags/v2017.09.04.02 --depth 1 https://github.com/facebook/buck.git $HOME/buck
  - cd $HOME/buck
  - ant
  - $HOME/buck/bin/buck --version

script:
  - $HOME/buck/bin/buck test --all

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/buck/
