dist: trusty
language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant
  # Install Buck
  - test -d $HOME/.buck || git clone --branch v2017.09.04.02 --depth 1 https://github.com/facebook/buck.git $HOME/.buck
  - ls $HOME/.buck
  - cd $HOME/.buck; ant
  - $HOME/.buck/bin/buck --version

script:
  - $HOME/.buck/bin/buck test --all

branches:
  except:
    - gh-pages

cache:
  directories:
    #- $HOME/buck/
