# //lib:

prebuilt_jar (
    name = 'jcsp',
    binary_jar = 'jcsp-1.1-rc5.jar',
    visibility = ["PUBLIC"],
)

prebuilt_jar (
    name = 'junit',
    binary_jar = 'junit-4.12.jar',
    deps = [':hamcrest-core'],
    visibility = ["PUBLIC"],
)

prebuilt_jar (
    name = 'hamcrest-core',
    binary_jar = 'hamcrest-core-1.3.jar',
)

