# //compiler:

java_library(
    name = 'syntax',
    srcs = glob(['*.java']),
    deps = [
        '//compiler/src/ca/junctionbox/cljbuck/channel:channel',
        '//compiler/src/ca/junctionbox/cljbuck/lexer:lexer',
        '//build/src/ca/junctionbox/cljbuck/build/json:json',
    ],
    visibility = ["PUBLIC"],
)
