# //compiler:

java_library(
    name = 'lib',
    srcs = glob(['src/**/*.java']),
    deps = ['//lib:jcsp', '//lib:guava',],
    visibility = ['PUBLIC'],
)

java_test(
    name = 'test',
    srcs = glob(['test/**/*.java']),
    deps = ['//lib:jcsp', '//lib:junit', '//lib:hamcrest-core', ':lib',],
)

java_binary(
    name = 'main',
    main_class = 'ca.junctionbox.cljbuck.Main',
    deps = [':lib'],
)

